[package]
name = "typst-lsp"
version = "0.4.1"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.71"
# TODO: In development, Typst depends on comemo as a git dependency. Update this
# to use crates.io when we can use a stable Typst version.
comemo = { git = "https://github.com/typst/comemo.git" }
dirs = "5"
elsa = { git = "https://github.com/nvarner/elsa.git" }
futures = "0.3"
if_chain = "1"
itertools = "0.10.5"
lazy_static = "1.4.0"
memmap2 = "0.5"
once_cell = "1"
parking_lot = "0.12.1"
regex = "1.8.1"
same-file = "1"
serde_json = "1.0.94"
siphasher = "0.3"
tokio = { version = "1.26.0", features = [
    "macros",
    "rt-multi-thread",
    "io-std",
] }
tower-lsp = "0.19.0"
# TODO: Update comemo alongside typst
typst = { git = "https://github.com/typst/typst.git", rev = "27771bc329ab23cc551637fb3feac7b5689e64c7" }
typst-library = { git = "https://github.com/typst/typst.git", rev = "27771bc329ab23cc551637fb3feac7b5689e64c7" }
unscanny = "0.1"
walkdir = "2"
